### ISSUE TITLE
Not recognized as a driver without driver_name and driver_version

### ISSUE THREAD

**Issue by johnac5cv** [poblabs/weewx-ObserverIP#1]
Your observerip.py was not recognized by my new installation of weewx...until I compared the structure with weewx-supplied drivers--they all had the DRIVER_NAME and DRIVE_VERSION. So, I added these lines right after the "import" statements, and it was immediately found by the weewx_config:
**DRIVER_NAME = 'ObserverIP'
DRIVER_VERSION = '1.0'**

**Comment by poblabs** [comment]
@johnac5cv Thanks! I updated this in the new commit. https://github.com/poblabs/weewx-ObserverIP/commit/b1864d6a80c1e8d798a691cf005463d635252385

Also, just a word on this driver and ObserverIP in general. I found that the ObserverIP locks up after being screen scraped. I think it was about 45 minutes of lockup (unresponsiveness) for every 24 hours of screen scraping. 

So I wrote a completely new driver and new method to get the data off the ObserverIP. It's more involved, but much more reliable and WeeWX is updated on a push interval, instead of a pull interval. Allows you to also have live data on your website if that's something you're into. 

Just something to consider. 

Here's the writeup: http://obrienlabs.net/redirecting-weather-station-data-from-observerip/
Here's the driver: https://github.com/poblabs/weewx-socketlogger

**Comment by johnac5cv** [comment]
Thanks for the reply. Yes, I saw your very clever workaround (pretending to be WXUnderground), and may eventually go there, since I have a half dozen LinkSys routers laying around (re [ham radio mesh](http://www.hotarc.org/mesh/) project). This screen scraping was a first order fix (after replacing my old WX station with the WS-1400ip), and I [have it working fine](http://ac5cv.dyndns.org/) (so far) using 60-sec scraping.

**Comment by poblabs** [comment]
@johnac5cv Yeah the 60 second scrape might work just fine. I think my 15 second scrape was annihilating it :)
